#MYSQL
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://budtree-db:3306/budtree_app?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
  #     format_sql: true
  ai:
    openai:
      api-key: ${GPT_KEY}
      chat:
        options:
          model: ${FINE_TUNNING_KEY}
          temperature: 1.0

  jwt:
    secret: ${JWT_KEY}

  redis:
    data:
      host: budtree-redis
      port: 6379
      database: 0

# Reverse Poxy to Spring boot header setting
server:
  forward-headers-strategy: native

###logging:
###    level:
###      root: trace